name: barcode_scanner
description: A new Flutter prototype.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <=3.10.2'
dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
